packages/core/src/constants.ts, packages/core/src/store/getters.ts, packages/ui/src/Popup/Signing/Request.tsx, packages/ui/src/Popup/Signing/index.tsx
Also:
- Wrap signing dialog details with a scrollable container.
- Set default network to `Alcyone`.
- Bring `Reject` button to signing dialog, in case user had saved their password.
=> Signing: display the signer account rather than the selected one

packages/core/src/background/handlers/Tabs.ts, packages/core/src/background/types.ts, packages/core/src/constants.ts, packages/core/src/utils.ts
Accessing Polkadot/apps using Polymesh wallet, user will be asked to inject network metadata (token name, decimals...etc), into that wallet. That is a useful feature for a network agnostic wallet such as Polkadot, but not to our network-specific wallet. Hence, this PR removes handling of those requests because otherwise, user wallet will popup and leave user confused about how to proceed.
To test, go the following tab in polkadot/app, and make sure that clicking on "update" does nothing at all.
=> Remove handling of meta injection requests

packages/ui/src/Popup/Authorize/Request.tsx
=> Auth dialog: display hostname only instead of full url

packages/ui/src/Popup/Accounts/AccountView.tsx, packages/ui/src/Popup/Accounts/AccountsHeader.tsx, packages/ui/src/ui/TextOverflowEllipsis/TextOverflowEllipsis.tsx, packages/ui/src/ui/TextOverflowEllipsis/index.ts, packages/ui/src/ui/index.ts
Demo: https://polymath.atlassian.net/browse/WAL-122?focusedCommentId=15747
✅ Badge should be vertically aligned with balance display as well, while not overlapping with the selection checkmark.
Used CSS grids + flex to define the layouts for account details + hover state for unassigned accounts.
✅ Names should have max width and then elipsises. 
Created a new `TextOverflowEllipsis` component which requires a `maxWidth`; if text inside overflows it will use "..." as the last characters (CSS only).
⛔️ (optional) Preferably, both secondary and primary badged should have the same width.
I thought it looked nice as it is, I experiemented with uniform badge widths, I actually thought the current way is fine/better in comparison. For refernce, this is how it looks with uniform widths:
Let me …
=> feat: update account card UI (WAL-122)

packages/ui/src/Popup/AccountDetails/index.tsx
=> fix: ellipsize text overflow for name display in account details

packages/ui/src/Popup/Accounts/AccountsContainer.tsx
I was tinkering around with this bug, and then I realized the reason for this "illusion" is because the account cards are _transparent_, i.e. the shadows are showing _through_ them not on top of them 😂
Simply adding a background color (white) solves the issue!
Example:
=> fix: add background color to account card to make it not-transparent (WAL-89)

__tests__/wallet.spec.ts, packages/ui/src/components/AccountDetails.tsx, packages/ui/src/components/Password.tsx
- added information text to clarify using current wallet password; let me know if the copy should be changed!
- changed password input placeholder text to specify the current wallet password
Screenshot:
=> feat: wallet password UI clarification (WAL-112)

packages/core/src/external/apiPromise/index.ts, packages/core/src/external/callDetails.ts
@wahidrahim this PR addresses two issues:
- We initialize API object every time `apiPromise` function is called. The issue here is that api will end up being initialized _twice_ if user is signing a tx. Once when popup opens, and the other when `callDetails` is called. Adding `reinitialize` argument to `apiPromise`, ensures that we don't recreate API unnecessarily.
- When WS connection fails, because a node is down, or because the node url is bad, ApiPromise will retry the connection 1500 times, which means that user would look at an inifinite spinner. This PR attempts to catch those errors and display them.
To test WS connection issues, edit the url of Alcyone network in `src/core/constants`. You'll find that wallet will display an error when you switch network to Alcyone, but error …
=> Better API management

packages/core/src/background/handlers/State.ts, packages/extension/public/index.html, packages/extension/public/notification.html, packages/ui/src/Popup/Accounts/AccountView.tsx, packages/ui/src/createView.tsx, packages/ui/src/hooks/useIsPopup.ts
- Increased the width of the wallet popup to 400px as per design suggestions
- Adjusted displaying account info to take up more space
Screenshots:
=> Increase wallet width

packages/ui/src/Popup/Accounts/AccountView.tsx, packages/ui/src/Popup/Accounts/index.tsx, packages/ui/src/Popup/ImportLedger/ImportLedger.tsx
- Omits “export” option in account menu for Ledger accounts
- Omits “change password” option when the wallet does not have any non-hardware accounts
- Changed copy "Account type" to "Account index" and "Account index" to "Address offset", to match data
- Increments `accountIndex` and `addressOffset` values to next available pair by default.
Increments `addressOffset` value before incrementing `accountIndex`, i.e. finds pairs in this index/offset pattern: 0/0, 0/1, 0/2, ..., 19/18, 19/19
Known issues:
- changing `accountIndex` or `addressOffset` does not automatically change its counterpart value
For example: 
```
- the index/offset is set to 0/1
- user changes the index to 1
- the offset is still at 1 (should be 0, if 1/0 is free)
```
=> Ledger integration fixes

packages/ui/src/Popup/ForgetAccount/index.tsx, packages/ui/src/messaging.ts
Require password input and validating password before forgetting an account, unless it's a Ledger account, in which case no password validation is required.
Screenshot:
=> [WAL-142][SEV1] authorize user before deleting an account

packages/ui/src/Popup/Signing/Request.tsx, packages/ui/src/Popup/Signing/Unlock.tsx
An authorized app may cause a temporary denial of service by sending a malformed extrinsic.sign request, and make the victim to restart his/her browser to able to use the wallet again.
To reproduce, you can send this message to the extension from your browser's console. Make sure you're browsing an app that has been authorised previously (eg token studio or polkadot apps).
```
var msg = {"id":"0.1","message":"","origin":"page","request":{"address":"5GpHvX9RRr8ZcJHcGcWQrR56wtNLcwi3CF1sDqVKvu395XRA","blockHash":"0x95a1a4fe9b4e4543e76e2108d6242ca881a5ad5be6cb06eea1aee24b218277d8","blockNumber":"0x003039e6","era”:”'”,”genesisHash":"0x12fddc9e2128b3fe571e4e5427addcb87fcaf08493867a68dd6ae44b406b39c7","method":"0x0400ff5a2657cbdd86be4ceb4d34eda4ec80668d58c96825a8bba657ddd0e1f785581c02093d00","non …
```
=> Issue #6: error handling for extrinsicSign

packages/ui/src/Popup/Accounts/AccountView.tsx
Previously account selections were made by clicking the initial-avatar circle, which was a bit unintuitive.
This PR allows selecting an account by clicking any part of the account card — that does not already have a clickable action, i.e. copy and edit.
This makes account selection easier and feels more natural. Please try it out!
=> [WAL-127] improve account selection

packages/core/src/background/handlers/Tabs.ts, packages/core/src/utils.ts
It can be really confusing when user imports an ITN-specific uid, while Alcyone is the active network in their wallet. After this PR, uid provision request handler well validate the provided network against the selected one, then throw an error if they mismatch.
=> Validate uid provision network

lerna.json, package.json, packages/core/package.json, packages/core/src/background/handlers/Tabs.ts, packages/extension/package.json, packages/extension/src/background.ts, packages/ui/package.json, packages/ui/src/Popup/Accounts/AddAccount.tsx
- Remove "Connect Ledger" option from wallet's onboarding screen.
- Fix an issue that is manifested as shown in the steps below. The problem was that we didn't hydrate the Redux store (which includes the selected account, amongst other data), until user open wallet popup. If they don't, we don't hydrate Redux store, and hence, no account appears as selected. The solution was to hydrate Redux store as soon as an App or the wallet Popup connect to wallet.
- Wallet gets updated from chrome store OR user reloads the extension deliberately from extensions page.
- User visits Fractal.
- When the app queries the selected user, the wallet returns with an error that `No account is present or no account selected`.
- Another issue of similar nature occurs when Fractal creates DID and uID in one go, …
=> Misc fixes + 0.5.4

packages/ui/src/Popup/Accounts/NetworkSelector.tsx, packages/ui/src/Popup/Accounts/index.tsx, packages/ui/src/components/OptionSelector.tsx, packages/ui/src/components/index.ts
- created OptionSelector component that shows dropdown options that can be attached to any component
- can add categories for options. E.g. "Networks", "Developer" text in the network selector options — this segregration is not included in this PR, just as an example:
<p align="center">
</>
- refactor NetworkSelector to use OptionSelector
- replace context-menu with OptionSelector for top menu options:
<p align="center">
</p>
- currently OptionSelector supports opening in bottom-left and bottom-right positions. More positioning options can be added as needed
- specifying positions also makes UI more predictable, especially for button clicks. But it is unlike a context-menu where it calculates where to open based on click coordinates. This is especially good for showing right-click options …
=> [WAL-125][WAL-166] Option selector component

packages/ui/src/Popup/Accounts/NetworkSelector.tsx, packages/ui/src/components/OptionSelector.tsx
Segregates production and development networks in the network selector in different categories:
=> add development network seperation in network selector

lerna.json, package.json, packages/core/package.json, packages/core/src/background/handlers/index.ts, packages/core/src/background/types.ts, packages/core/src/constants.ts, packages/core/src/page/index.ts, packages/extension/package.json, packages/extension/src/content.ts, packages/extension/src/page.ts, packages/ui/package.json, packages/ui/src/Popup/Signing/SignArea.tsx
The goal of this PR is not punish our users by having them disable Polkadot, ChainX, or any wallet that exposes the same API. While that requirement/restriction is ok to apply on our own app, we cannot force 3rd party developers to block users that have non-Polymesh wallets installed.
This PR changes the source property of messages coming from the injected script, in order to distinguish them from Polkadot's. It enables users to have have both wallets installed, and even authorized on a dapp, but as long as the dapp targets `polywallet` injected object, things should work fine. 
You can test the PR against [mock-uid-provider](https://polymathnetwork.github.io/mock-uid-provider/) tool, while having both wallets installed and authorized.
Before 
After
=> [WAL-168] Change the source of the messages that are send from injected script

lerna.json, package.json, packages/core/package.json, packages/core/src/background/handlers/Extension.ts, packages/core/src/background/types.ts, packages/extension/package.json, packages/ui/package.json, packages/ui/src/Popup/Accounts/index.tsx, packages/ui/src/Popup/ChangePassword/index.tsx, packages/ui/src/messaging.ts
- Fix a bug where old password were used as the new password, rendering password change operation useless.
- Open password change screen in a separate tab, to make the operation less likely to interrupt.
- Filter ledger accounts out of the accounts the receive password change.
- Inform user to contact Polymath if password change failed. We will have to help them more closely in that case.
=> Fix password change logic

packages/ui/src/ui/Checkbox/Checkbox.tsx
Quick fix to enable checkbox toggling by clicking label text. Main changes are:
- use only one `label` element
- the nested `label`s were causing the issue where clicking the label text wouldn't automatically trigger the checkbox, _if_ a name is not provided.
- fix lint warning
=> toggle checkbox by clicking label text

packages/ui/src/Popup/Accounts/index.tsx, packages/ui/src/Popup/ImportLedger/ImportLedger.tsx, packages/ui/src/components/Dropdown.tsx
- show correct address format on Mainnet for Ledger account imports
- update UI on Ledger account imports
- prevent opening Ledger imports on new tabs, if already in a tab
- move the "Unassigned keys" group back to the bottom
- refactor code
=> fix: Import Ledger account popup

packages/core/src/constants.ts, packages/ui/src/Popup/AppHeader/AppHeader.tsx
Clicking "Go to Dashboard" link on wallet when connected to "Local" network, it opens a page to "http://localhost:3000"
=> fix: use localhost link for dashboard for local network

packages/ui/src/Popup/Accounts/AddAccount.tsx
new window. This prevents popup accidentally closing.This prevents popup accidentally closing when clicking away from the popup. e.g. to paste the seed into a password manager.
copied from: https://github.com/PolymeshAssociation/polymesh-wallet/pull/254
=> fix: open initial create/import account screens as

package.json, packages/core/src/background/handlers/Tabs.ts, packages/core/src/background/types.ts, packages/core/src/page/Network.ts, packages/ui/src/styles/utils.ts, yarn.lock
- Add the ability to unsubscribe from `accounts`.
- Add the ability to unsubscribe from `network` information.
- `accounts.subscribe` now returns account details on initial subscription. This is in line with other polkadot extension based wallets.
- `network.subscribe` now returns network details on initial subscription.
The implementation of the subs & unsubs uses a similar approach to the polkadot/extension-base methods which are overridden for accounts by the polymesh/extension-core https://github.com/polkadot-js/extension/blob/3c35c2bcd5b5c4657fb597915d86368b1386994c/packages/extension-base/src/background/handlers/Tabs.ts#L79
=> Fix Account and Network Unsubscribing

CHANGELOG.md, README.md, package.json, packages/core/package.json, packages/core/src/external/callDetails.ts, packages/core/src/page/injected.ts, packages/extension/package.json, packages/ui/package.json, packages/ui/src/Popup/Signing/LedgerSignArea.tsx, packages/ui/src/Popup/Signing/Request.tsx, packages/ui/src/hooks/useLedger.ts, packages/ui/src/ui/Loading/Loading.tsx, packages/ui/src/ui/Loading/styles.ts, yarn.lock
- When signing if a the wallet is missing permissions to connect to a ledger over USB display
After opening the extension in a window clicking the connect button will trigger the permissioning flow for the USB device. 
Permissioning must be triggered by a user action requiring them to explicitly click connect.
- Fix showing protocol fees for `AssetRegisterUniqueTicker`
- Show protocol fees for nested calls
- Update to lastest Polymesh SDK and types bundles
- Add SignedExtension definitions when calling registry.setSignedExtensions to prevent the unknown signedExtension StoreCall Metadata warning.
- Update `PolymeshInjected` so it will no longer trigger an ongoing ping message which was causing console errors after not interacting with a dApp for a period of time. 
- Fix loading spinner
=> Improve flow for troubleshooting Ledger connection and misc other changes

packages/core/src/store/accountMigrations.ts, packages/extension/src/background-init.ts, packages/extension/src/migrations.ts
- Call `initializeCryptoAndKeyring` in all cases.
- If account migrations take place reload the extension to update the accounts in the keyring from the migrated storage.
=> fix: ensure keyring is always initialized

CHANGELOG.md, package.json, packages/core/package.json, packages/core/src/index.ts, packages/extension/package.json, packages/extension/src/page.ts, packages/ui/package.json, packages/ui/src/Popup/Authorize/Request.tsx, packages/ui/src/Popup/Signing/LedgerSignArea.tsx, packages/ui/src/Popup/Signing/SignArea.tsx, packages/ui/src/messaging.ts, yarn.lock
- Update to latest upstream Polkadot dependencies
- Canceling an authorization request now resolves the promise with an error instead of leaving unresolved
- Ensure extension is injected as early as possible instead of waiting for phishing checks to complete 
- Change "Reject" buttons to "Cancel"
- Remove secondary key checks that were required for v6 compatibility.
=> Bump deps + miscellaneous minor updates
