PolymeshAssociation/polymesh-wallet

packages/ui/src/Popup/ImportJson/index.tsx

When importing JSON while having existing accounts, change the imported account password after import.

Fix: JSON Import

---

packages/ui/src/Popup/ChangePassword/index.tsx
packages/ui/src/Popup/ExportAccount/index.tsx
packages/ui/src/Popup/ImportJson/index.tsx
packages/ui/src/Popup/ImportSeed/AccountDetails.tsx
packages/ui/src/Popup/ImportSeed/EnterSeed.tsx
packages/ui/src/Popup/NewAccount/AccountDetails.tsx
packages/ui/src/Popup/NewAccount/ConfirmSeed.tsx
packages/ui/src/Popup/NewAccount/SeedView.tsx
packages/ui/src/ui/Header/Header.tsx

- Add cancel button to header component to show if the path is not '/';
- Move the text and icon to the. header component
- Modify components that consume the header

Feat: Cancel button

---

packages/core/src/api/apiPromise/schema.ts
packages/core/src/constants.ts
packages/core/src/index.ts
packages/core/src/store/getters.ts
packages/core/src/store/selectors.ts
packages/ui/src/Popup/ImportJson/index.tsx

- Delete accounts that, for some reason, remain in redux, after they had been forgotten from keyring.
- Remove `isHidden` key from account's metadata before importing.
- Update schemas
- Made PME the default network.

See description

---

package.json
packages/core/src/api/apiPromise/index.ts
packages/core/src/background/handlers/Extension.ts
packages/core/src/background/handlers/index.ts
packages/core/src/background/types.ts
packages/core/src/index.ts
packages/core/src/store/features/status.ts
packages/core/src/store/index.ts
packages/core/src/store/selectors.ts
packages/core/src/store/setters.ts
packages/core/src/store/subscribers.ts
packages/core/src/types/index.ts
packages/core/src/utils.ts
packages/extension/manifest.json
packages/extension/src/background.ts
packages/extension/src/extension.ts
packages/ui/package.json
packages/ui/src/Popup/Accounts/AddAccount.tsx
packages/ui/src/Popup/index.tsx
packages/ui/src/messaging.ts
packages/ui/src/ui/Toast/index.tsx
packages/ui/src/ui/Toast/styles.ts
yarn.lock

Errors will be caught an sent to the front-end through a subscription:
- Fatal errors will be displayed in ErrorBoundaryFallback.
- Non-fatal errors will be displayed in Toast.
Few tiny copy changes:
- WAL-56: Renamed wallet to "Polymesh Wallet".
- WAL-57: Change wording of account addition buttons.

Background error handling

---

packages/ui/src/Popup/Accounts/AccountView.tsx
packages/ui/src/Popup/Accounts/AccountsHeader.tsx
packages/ui/src/Popup/NewAccount/AccountDetails.tsx
packages/ui/src/ui/BaseInput/BaseInputProps.tsx
packages/ui/src/ui/BaseInput/styles.ts
packages/ui/src/ui/LabelWithCopy/LabelWithCopy.tsx

- Alias editing textfield unnecessarily tall that it increases the height of the surrounding component.
- All “copy” icons that appear on hover, never disappear, on blur.

Fix: Misc styling issues (WAL-46)

---

packages/ui/src/Popup/Authorize/Request.tsx

Fix: auth dialog buttons

---

packages/ui/src/Popup/ImportJson/UploadVerifyJson.tsx

Fix: change to Polymesh Wallet (WAL-86)

Fix: capitalization (WAL-86)

---

lerna.json
package.json
packages/core/package.json
packages/core/src/api/apiPromise/schema.ts
packages/core/src/index.ts
packages/extension/package.json
packages/ui/package.json
packages/ui/src/Popup/index.tsx

Api initiatization fails on PME after a recent upgrade. That results in an infinite loader when selecting PME network, or if it's the currently selected one.
This PR updates schema and also changes signature of DID chainstate query.

pme updates

---

packages/core/src/api/apiPromise/schema.ts
packages/core/src/background/handlers/Extension.ts
packages/core/src/background/types.ts
packages/core/src/constants.ts
packages/core/src/store/features/network.ts
packages/core/src/store/selectors.ts
packages/core/src/store/setters.ts
packages/core/src/store/subscribers.ts
packages/ui/src/Popup/Accounts/index.tsx
packages/ui/src/Popup/index.tsx
packages/ui/src/messaging.ts
packages/ui/src/types.ts

[WIP] Let user reveal/hide development networks

---

packages/ui/src/Popup/Signing/Request.tsx
packages/ui/src/components/Warning.tsx

- fix margin/padding
- update warning component
- slightly improve button sizing
screenshot:

Signing UI fixes

---

packages/ui/src/Popup/ProvideUidRequests/Request.tsx
packages/ui/src/Popup/ProvideUidRequests/index.tsx

Removed conditionally disabling scrolling. Please check if it breaks something else; I was not sure why it was necessary. It's working as what I would think is the expected behavior.

WAL-132: fix inability to scroll

---

packages/core/src/background/handlers/Extension.ts
packages/core/src/background/handlers/Tabs.ts
packages/core/src/background/types.ts
packages/core/src/constants.ts
packages/core/src/external/apiPromise/index.ts
packages/core/src/external/polyNetworkSubscribe.ts
packages/core/src/external/schema/fallback.ts
packages/core/src/index.ts
packages/core/src/store/features/network.ts
packages/core/src/store/getters.ts
packages/core/src/store/selectors.ts
packages/core/src/store/subscribers.ts
packages/core/src/types/index.ts
packages/core/src/utils.ts
packages/ui/src/Popup/AccountDetails/AccountView.tsx
packages/ui/src/Popup/AccountDetails/index.tsx
packages/ui/src/Popup/Accounts/AccountView.tsx
packages/ui/src/Popup/Accounts/AccountsContainer.tsx
packages/ui/src/Popup/Accounts/AccountsHeader.tsx
packages/ui/src/Popup/Accounts/index.tsx
packages/ui/src/Popup/ImportJson/UploadVerifyJson.tsx
packages/ui/src/Popup/ImportLedger/ImportLedger.tsx
packages/ui/src/Popup/ProvideUidRequests/Request.tsx
packages/ui/src/Popup/Restore/components/UploadJson.tsx
packages/ui/src/Popup/Signing/Request.tsx
packages/ui/src/Popup/index.tsx
packages/ui/src/components/contexts.tsx
packages/ui/src/messaging.ts
packages/ui/src/types.ts

- Accounts storage in Keyring hasn't changed. They are always stored with the default, chain-agnostic format.  Check local storage.
- However, we will respect the current chain format, on display.

Respect chain ss58Format

---

packages/core/src/constants.ts

As per Fractal's [request](https://polymathnetwork.slack.com/archives/C0126848SKB/p1617019332035300)

add fractal staging url to whitelist

---

packages/ui/src/Popup/Accounts/AccountView.tsx
packages/ui/src/Popup/Accounts/NameEdit.tsx
packages/ui/src/Popup/Accounts/styles.ts
packages/ui/src/ui/TextOverflowEllipsis/TextOverflowEllipsis.tsx

This PR adds refactors and the following UI/UX updates:
before:
after:
before:
after:

Account view updates

---

packages/ui/src/Popup/Signing/LedgerSignArea.tsx
packages/ui/src/Popup/Signing/Request.tsx
packages/ui/src/Popup/Signing/SignArea.tsx
packages/ui/src/Popup/Signing/Unlock.tsx
packages/ui/src/Popup/Signing/index.tsx

- Fix the "save pass for 15 mins" issue.
- Move ledger signing to a separate component.
- Break `Singing/Request` down into smaller components.
Things to test:
- Signing tx using regular account still works.
- Signing tx using Ledger account still works.
- Make sure the darn pass is really saved for 15 mins.

[WAL-130] Re-arrange signing components

---

packages/ui/package.json
packages/ui/src/Popup/AccountDetails/AccountView.tsx
packages/ui/src/Popup/Accounts/AccountView.tsx
packages/ui/src/Popup/Accounts/AccountsHeader.tsx
packages/ui/src/Popup/Signing/Extrinsic.tsx
packages/ui/src/util/formatters.ts
yarn.lock

- Network, Protocol and Total fees should be displayed as `0.096 POLYX` instead of `96 m POLYX`, which can be interpreted as 96 million PolyX!
- Remove `bignumber.js` in favour of the already existing `bn.js`.

WAL-111: Fix fees display

---

packages/ui/src/Popup/Accounts/index.tsx
packages/ui/src/components/OptionSelector/OptionItem.tsx
packages/ui/src/components/OptionSelector/index.tsx
packages/ui/src/components/OptionSelector/styles.ts
packages/ui/src/components/OptionSelector/types.ts

- fixes "Connect Ledger device" option not showing
- disables "Attach Ledger account" option if browser is incapable
- adds an option to disable option item in OptionSelector component

[WAL-185] fix showing ledger options

---

packages/core/src/constants.ts
packages/core/src/external/schema/fallback.ts
packages/core/src/external/schema/v4.0.0.ts
packages/core/src/types/index.ts
packages/ui/src/Popup/Accounts/NetworkSelector.tsx
packages/ui/src/Popup/ImportLedger/TroubleshootGuide.tsx

feat(UI): add Testnet network selector

---

packages/core/src/constants.ts

(cherry picked from commit 9d25a71966d1cf9914e560cb3f1a9e2b88ff7dba)

fix: remove trailing slash in url

---

packages/ui/src/Popup/Accounts/index.tsx
packages/ui/src/Popup/Signing/LedgerSignArea.tsx
packages/ui/src/util/chains.ts

- add genesis hash for Mainnet
- use correct genesis hash for Tooling
- fix button widths when signing with Ledger
- open Ledger related popups on new tabs always, to get around browser USB permission issues

fix: genesis hash issues with Ledger devices

---

packages/core/src/constants.ts
packages/ui/src/Popup/Accounts/NetworkSelector.tsx
packages/ui/src/Popup/ImportLedger/ImportLedger.tsx
packages/ui/src/assets/mainnet-circle.svg
packages/ui/src/components/Warning.tsx

- use Mainnet as the default network to connect to from wallet installation
- new Mainnet "gradient" circle in network selector
- fix styling for warnings and errors for Ledger transaction signing

feat: default to Mainnet from wallet installation

---

packages/ui/src/Popup/Signing/Extrinsic.tsx
packages/ui/src/Popup/Signing/Request.tsx
packages/ui/src/Popup/Signing/SignArea.tsx

- checks if there is enough POLYX available to pay for fees
- refactor to bring calculations up higher on the components tree
- disable signing button and show "Insufficient funds" if unable to pay for fees

fix: disable signing if insufficient balance [GTN-2297] [GTN-2162]

---

__tests__/wallet.spec.ts
packages/core/src/constants.ts
packages/core/src/external/schema/fallback.ts
packages/core/src/types/index.ts
packages/ui/src/Popup/Accounts/NetworkSelector.tsx
packages/ui/src/util/chains.ts

- remove Tooling and Staging development networks
- update e2e tests to run on Testnet

fix: remove tooling and staging networks [GTN-2317]

---

packages/ui/src/Popup/ImportLedger/ImportLedger.tsx

fix: switch to appropriate genesis hash

---

packages/extension/package.json

chore: update dependencies

---

packages/core/src/constants.ts
packages/ui/src/ui/GrowingButton/styles.ts

Replace dashboard links with portal links
Copied from: https://github.com/PolymeshAssociation/polymesh-wallet/pull/256

chore: replace dashboard links with portal links
